# Generated by Django 3.2.7 on 2021-09-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_code', models.CharField(max_length=5)),
                ('c_name', models.CharField(max_length=150)),
                ('semester', models.IntegerField()),
                ('a_year', models.IntegerField()),
                ('count_stu', models.IntegerField(default=0)),
                ('max_stu', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
