# Generated by Django 3.2.6 on 2021-09-13 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_take'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='take',
            name='student',
        ),
        migrations.AddField(
            model_name='take',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='takes', to=settings.AUTH_USER_MODEL),
        ),
    ]
